### ISSUE TITLE
Computational cost

### ISSUE THREAD

**Issue by tomkimsour** [sphanit/CoHAN_Planner#1]
In your papers, you test your planning algorithm on pepper robot with an ethernet cable. Which makes me assume you compute the code on an external machine.
Thus, I was wondering if the computational cost low enough to run on pepper robot ?

**Comment by sphanit** [comment]
Yes, we use an external machine to run the code and send the commands to Pepper via ethernet or wifi. However, the compiled code was able to run the local planner at 8Hz on a virtual machine using 2-4 processor cores and RAM > 2GB. So, I think you should be able to run it on Pepper, probably at 4-5Hz, but it's not guaranteed. We did not run the code directly on the robot as it is not straight forward to compile and run ROS on Pepper.
