### ISSUE TITLE
Planner unable to approach the goal pose, robot infinitely oscillates

### ISSUE THREAD

**Issue by rayvburn** [sphanit/CoHAN_Planner#2]
Hello,

I've encountered a strange behaviour with CoHAN planner. **When a goal pose is relatively close to an obstacle**, the robot reaches a pose that is shifted to the side and then cannot unstuck to reach the requested goal (that is located approx. 30 cm further). I tested the planner with a TIAGo robot and the issue occurs both with a simulated setup and the real hardware.

The issue is visualized below (the green arrow above the robot represents current command of the mobile base):
![cohan3](https://user-images.githubusercontent.com/28673246/222983352-83ff482e-9d7b-47e5-9d8e-ac6d2362f8a6.gif)

At first I thought that the planner assumes that it operates with a holonomic robot, but the commanded y-velocity is zero:
![image](https://user-images.githubusercontent.com/28673246/222982966-06f2ded2-4ff3-4832-8ad7-09ee8a71315a.png)

What's more, I think that the same issue causes ignoring (in planner's trajectories) round corners that are marked in the global plan. This causes the robot to collide sometimes in L-shaped corridors. The behaviour of "cutting corners" of the global plan can be observed in the example above but in this case collision did not occur.

Can this issue be managed with some parameter tuning?

**Comment by sphanit** [comment]
Hello, 

This should ideally be solved using parameter tuning. You might need to set the weight of non-holonomic behaviour in the optimization to a large value, like 500 or 1000. The second thing that can cause issues sometimes is acceleration. You might increase the limits a bit and check if this behaviour persists. If you want to track the global path very closely, you can change the max_global_plan_lookahead_dist from 0 to 2 (0 means full (10m), 2 means look ahead only 2 metres). I hope this fixes your issues.

**Comment by rayvburn** [comment]
Hello,

thanks for the hint.
Increasing the `weight_kinematics_nh` seems to improve the behaviour. The robot stops these strange forward-backwards motions and cutting through corners when `weight_kinematics_nh` is set to values above `40.0`. Additionally, I've set `weight_kinematics_turning_radius` to `1` (was `0`) that helped robot being stuck in narrow corridors.
